---
checks:
  # Exclude checks that are too strict for example/reference files
  doNotAutoAddDefaults: false
  exclude:
    # Allow missing service accounts (might not exist yet)
    - non-existent-service-account
    # Allow port mismatches in example files
    - liveness-port
    - readiness-port
    # Allow missing labels/annotations (optional metadata)
    - required-annotation-email
    - required-label-owner
    # Allow latest tags in examples (not production)
    - latest-tag
    # Allow missing probes in example pods/jobs
    - no-liveness-probe
    - no-readiness-probe
    # Allow missing anti-affinity in examples
    - no-anti-affinity
    # Allow unset resources in example/test pods
    - unset-cpu-requirements
    - unset-memory-requirements
    # Allow dangling services (examples may not have matching pods)
    - dangling-service
    # Allow PDB without unhealthyPodEvictionPolicy (optional field)
    - pdb-unhealthy-pod-eviction-policy

  # Keep critical security checks enabled
  include:
    - deprecated-service-account-field
    - docker-sock
    - drop-net-raw-capability
    - env-var-secret
    - host-ipc
    - host-network
    - host-pid
    - mismatching-selector
    - no-extensions-v1beta
    - privilege-escalation-container
    - privileged-container
    - privileged-ports
    - sensitive-host-mounts
    - ssh-port
    - unsafe-proc-mount
    - unsafe-sysctls
    - writable-host-mount

# Ignore example/template files
ignorePaths:
  - k8s/examples/
  - k8s/templates/
  - '**/test/**'
