---
checks:
  # Exclude checks that are optional or not applicable
  doNotAutoAddDefaults: false
  exclude:
    # Allow missing service accounts (might not exist yet)
    - non-existent-service-account
    # Allow port mismatches in example files
    - liveness-port
    - readiness-port
    # Allow missing labels/annotations (optional metadata)
    - required-annotation-email
    - required-label-owner
    # Allow latest tags in example/reference files only
    - latest-tag
    # Allow dangling services in examples (may not have running pods)
    - dangling-service
    # Allow PDB without unhealthyPodEvictionPolicy (optional K8s 1.26+ field)
    - pdb-unhealthy-pod-eviction-policy

# Ignore example/template files
ignorePaths:
  - k8s/examples/
  - k8s/templates/
  - '**/test/**'
